#host
http.host: 0.0.0.0
node.name: logstash-node

#xpack
xpack.monitoring.elasticsearch.username: logstash_system
xpack.monitoring.elasticsearch.password: ${LOGSTASH_SYSTEM_PASSWORD}
xpack.monitoring.elasticsearch.hosts: ["http://elasticsearch:9200"]
