version: '3.0'

networks:
  kongnet:
    driver: bridge
volumes:
  postgresdata: {}

services:
  kong-db:
    image: postgres:${POSTGRES_VERSION}
    container_name: kong_db
    restart: always
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - kongnet
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kongpass

  kong-migration:
    image: kong/kong-gateway:${KONG_VERSION}
    container_name: kong_migration
    restart: on-failure
    command: "kong migrations bootstrap"
    networks:
      - kongnet
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_PASSWORD: kongpass
    depends_on:
      - kong-db
    links:
      - kong-db

  kong:
    image: kong/kong-gateway:${KONG_VERSION}
    container_name: kong
    restart: always
    networks:
      - kongnet
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
      - 8002:8002
      - 8445:8445
      - 8003:8003
      - 8004:8004

    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002
    depends_on:
      - kong-migration
      - kong-db


