spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: postgres
    password: 2292892000
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect