server:
  port: 8000

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tranbamanh229289/planck.git
          search-paths: plank-cloud/config-store
          default-label: master

eureka:
  client:
    service-url: http://localhost:8761