#server
server.name: kibana-server
server.host: 0.0.0.0
elasticsearch.hosts: [ http://elasticsearch:9200 ]

#monitoring
monitoring.ui.container.elasticsearch.enabled: true
monitoring.ui.container.logstash.enabled: true

#xpack
elasticsearch.username: kibana_system
elasticsearch.password: ${KIBANA_SYSTEM_PASSWORD}